In [3]:
import numpy as np

In [4]:
A = np.array([[5,1,0],[2,5,1],[1,1,6]])
print(A)

[[5 1 0]
 [2 5 1]
 [1 1 6]]


In [1]:
def Jacobi(A,b,epsilon):
    n = A.shape[0]
    D = np.diag(np.diag(A))
    L = - np.tril(A,-1)
    U = - np.triu(A,1)
    D_inv = np.linalg.inv(D)
    Lj = D_inv @ (L + U)
    radius = np.linalg.eigvals(Lj)
    if(np.max(abs(radius)) < 1):
        print("yes")
        X_cur  = np.zeros(n).reshape(n,1)
        r = b - A @ X_cur
        while(np.linalg.norm(r) >= epsilon):
            X_cur = Lj @ X_cur + D_inv @ b
            r = b - A @ X_cur
        return X_cur
    else:
        print("No convergence")
        return 0


In [5]:
Jacobi(A,[[6],[-4],[9]],10 ** (-4))

yes


array([[ 1.54477757],
       [-1.72386786],
       [ 1.5298557 ]])