In [2]:
import numpy as np

In [5]:
A = np.array([[1,2,3],[2,5,1],[0,2,3]])
print(A)

[[1 2 3]
 [2 5 1]
 [0 2 3]]


In [16]:
def OGD(A,b,epsilon):
    n = A.shape[0]
    X = np.zeros(n).reshape(n,1)
    r = b - A @ X

    while(np.linalg.norm(r) >= epsilon):
        temp = r.flatten()
        a = np.dot(temp,temp) / np.dot((A @ r).flatten(),temp)
        X += a * r
        r = b - A @ X
    
    return X


In [18]:
A = np.array([
    [4, 1, 1],
   [1, 3, -1],
    [1, -1, 2]
], dtype=float)

b = np.array([6, 3, 2], dtype=float)
b = b.reshape(b.shape[0],1)

res = OGD(A,b,0.00001)
print(res)


[[1.00000169]
 [0.9999955 ]
 [0.99999411]]
